// Generated by CoffeeScript 1.10.0
(function() {
  var build_about, build_gallery, build_info, build_investment, build_pups, build_routes, build_video, check_buttons, circleGeometry, cities, close_menu, close_popup, current_popup_data, ellipsoid, fly_to_home, geodata, get_img, get_oopt_rect, handler, insertByAjax, load_borders, load_cities, load_fz, load_geodata, load_np, load_popups_data, load_zp, oopt, open_menu, open_popup, pole_primitive, popups_data, prepare_popup, primitives, redCircleInstance, scene, selected_polygon_name, settings, viewer;

  geodata = [
    {
      name: "np",
      path: "ndata/dv/np-dv.topojson",
      color: "#d8b366"
    }, {
      name: "zp",
      path: "ndata/dv/zp-dv.topojson",
      color: "#7ab342"
    }
  ];

  settings = {
    home: [147, 60, 6000000.0],
    baseMap_ru: "kosmo",
    baseMap_en: "tile_run-bike-hike",
    dataPath: "data/",
    layerPath: "ndata/dv/"
  };

  viewer = new Cesium.Viewer('cesiumContainer', {
    timeline: false,
    baseLayerPicker: false,
    infoBox: false,
    navigationHelpButton: false,
    geocoder: false,
    animation: false,
    scene3DOnly: true,
    fullscreenButton: false,
    imageryProvider: Cesium.createOpenStreetMapImageryProvider({
      url: {
        "en": settings.baseMap_en,
        "ru": settings.baseMap_ru
      }[lang],
      maximumLevel: 10
    })
  });

  insertByAjax = function(url, container, callback) {
    return $.ajax({
      url: url,
      dataType: "html",
      success: function(data, textStatus) {
        container.html(data);
        if (callback) {
          return callback();
        }
      },
      error: function() {
        return container.empty();
      }
    });
  };

  build_about = function() {
    var about_url;
    about_url = {
      "en": "about.html",
      "ru": "about_ru.html"
    }[lang];
    insertByAjax(about_url, $(".copyright__info__inner"), function() {
      return $(".about__cesium-credit").append($(".cesium-viewer-bottom").detach());
    });
    $(".copyright__info-link").on("click", function(e) {
      e.stopPropagation();
      e.preventDefault();
      return $(".copyright__info").fadeToggle(100);
    });
    $(".copyright__info__close").on("click", function(e) {
      e.preventDefault();
      return $(".copyright__info").fadeOut(100);
    });
    return $(".copyright__info").on("click", function(e) {
      return e.stopPropagation();
    });
  };

  build_about();

  circleGeometry = new Cesium.CircleGeometry({
    center: Cesium.Cartesian3.fromDegrees(90.0, 90.0),
    radius: 560000.0,
    vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT
  });

  redCircleInstance = new Cesium.GeometryInstance({
    geometry: circleGeometry,
    attributes: {
      color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(0.71, 0.816, 0.816, 1))
    }
  });

  pole_primitive = new Cesium.Primitive({
    geometryInstances: [redCircleInstance],
    appearance: new Cesium.PerInstanceColorAppearance({
      closed: true
    })
  });

  pole_primitive.show = false;

  viewer.scene.primitives.add(pole_primitive);

  scene = viewer.scene;

  primitives = scene.primitives;

  oopt = {};

  popups_data = [];

  current_popup_data = {};

  selected_polygon_name = '';

  $('.fullscreen_btn').click(function() {
    if ($.fullscreen.isFullScreen()) {
      $.fullscreen.exit();
    } else {
      $('body').fullscreen();
    }
    return false;
  });

  viewer.homeButton.viewModel.command.beforeExecute.addEventListener(function(commandInfo) {
    fly_to_home();
    return commandInfo.cancel = true;
  });

  fly_to_home = function() {
    return scene.camera.flyTo({
      destination: Cesium.Cartesian3.fromDegrees(settings.home[0], settings.home[1], settings.home[2]),
      duration: 3
    });
  };

  scene.camera.flyTo({
    destination: Cesium.Cartesian3.fromDegrees(settings.home[0], settings.home[1], settings.home[2]),
    duration: 0
  });

  load_popups_data = function() {
    return $.getJSON(settings.dataPath + 'data.json', function(data) {
      return popups_data = data.data;
    });
  };

  load_popups_data();

  load_geodata = function() {
    var dataSource, data_item, j, len, results;
    results = [];
    for (j = 0, len = geodata.length; j < len; j++) {
      data_item = geodata[j];
      dataSource = new Cesium.GeoJsonDataSource();
      results.push(dataSource.load(data_item.path).then(function() {
        var entities, entity, k, len1, mat_property;
        viewer.dataSources.add(dataSource);
        entities = dataSource.entities.values;
        mat_property = new Cesium.ColorMaterialProperty(new Cesium.Color.fromCssColorString('rgba(208,177,125, .87)'));
        for (k = 0, len1 = entities.length; k < len1; k++) {
          entity = entities[k];
          if (entity.polygon) {
            entity.polygon.material = mat_property;
            entity.polygon.outline = new Cesium.ConstantProperty(false);
            entity.isNP = true;
            if (!oopt[entity.properties["Name_" + lang]]) {
              oopt[entity.properties["Name_" + lang]] = [];
            }
            oopt[entity.properties["Name_" + lang]].push(entity);
            oopt[entity.properties["Name_" + lang]]._id = entity.properties.ids_ID;
          }
        }
        return load_zp();
      }));
    }
    return results;
  };

  load_np = function() {
    var dataSource;
    dataSource = new Cesium.GeoJsonDataSource();
    return dataSource.load(settings.layerPath + "np-dv.topojson", {
      clampToGround: true
    }).then(function() {
      var entities, entity, j, len, mat_property;
      viewer.dataSources.add(dataSource);
      entities = dataSource.entities.values;
      mat_property = new Cesium.ColorMaterialProperty(new Cesium.Color.fromCssColorString('rgba(185, 132, 121,.87)'));
      for (j = 0, len = entities.length; j < len; j++) {
        entity = entities[j];
        if (entity.polygon) {
          entity.polygon.material = mat_property;
          entity.polygon.outline = new Cesium.ConstantProperty(false);
          entity.isNP = true;
          if (!oopt[entity.properties["Name_" + lang]]) {
            oopt[entity.properties["Name_" + lang]] = [];
          }
          oopt[entity.properties["Name_" + lang]].push(entity);
          oopt[entity.properties["Name_" + lang]]._id = entity.properties.ids_ID;
        }
      }
      return load_fz();
    });
  };

  load_np();

  load_fz = function() {
    var dataSource;
    dataSource = new Cesium.GeoJsonDataSource();
    return dataSource.load(settings.layerPath + "fz-dv.topojson", {
      clampToGround: true
    }).then(function() {
      var entities, entity, j, len, mat_property;
      viewer.dataSources.add(dataSource);
      entities = dataSource.entities.values;
      mat_property = new Cesium.ColorMaterialProperty(new Cesium.Color.fromCssColorString('rgba(208,177,125, .87)'));
      for (j = 0, len = entities.length; j < len; j++) {
        entity = entities[j];
        if (entity.polygon) {
          entity.polygon.material = mat_property;
          entity.polygon.outline = new Cesium.ConstantProperty(false);
          entity.isFZ = true;
          if (!oopt[entity.properties["Name_" + lang]]) {
            oopt[entity.properties["Name_" + lang]] = [];
          }
          oopt[entity.properties["Name_" + lang]].push(entity);
          oopt[entity.properties["Name_" + lang]]._id = entity.properties.ids_ID;
        }
      }
      return load_zp();
    });
  };

  load_zp = function() {
    var dataSource;
    dataSource = new Cesium.GeoJsonDataSource();
    return dataSource.load(settings.layerPath + "zp-dv.topojson", {
      clampToGround: true
    }).then(function() {
      var entities, entity, j, len, mat_property;
      viewer.dataSources.add(dataSource);
      entities = dataSource.entities.values;
      mat_property = new Cesium.ColorMaterialProperty(new Cesium.Color.fromCssColorString('rgba(105,131,40, .87)'));
      for (j = 0, len = entities.length; j < len; j++) {
        entity = entities[j];
        if (entity.polygon) {
          entity.polygon.material = mat_property;
          entity.polygon.outline = new Cesium.ConstantProperty(false);
          entity.isZP = true;
          if (!oopt[entity.properties["Name_" + lang]]) {
            oopt[entity.properties["Name_" + lang]] = [];
          }
          oopt[entity.properties["Name_" + lang]].push(entity);
          oopt[entity.properties["Name_" + lang]]._id = entity.properties.ids_ID;
        }
      }
      return build_pups();
    });
  };

  build_pups = function() {
    var billboards, center, color, dta, entity_key, j, k, key, keys, len, len1, rect, withInvest;
    billboards = scene.primitives.add(new Cesium.BillboardCollection());
    keys = [];
    for (key in oopt) {
      keys.push(key);
    }
    keys = keys.sort();
    for (j = 0, len = keys.length; j < len; j++) {
      entity_key = keys[j];
      withInvest = false;
      for (k = 0, len1 = popups_data.length; k < len1; k++) {
        dta = popups_data[k];
        if ((dta.id === "" + oopt[entity_key]._id) && dta.invest) {
          withInvest = true;
        }
      }
      $(".left_menu").append('<div>');
      $(".left_menu div:last-child").text(entity_key).on('click', function(e) {
        var rect, text;
        $('.popup').hide();
        text = $(this).text();
        rect = get_oopt_rect(text);
        scene.camera.flyTo({
          destination: rect
        });
        selected_polygon_name = text;
        setTimeout(open_menu, 100);
        return e.stopPropagation();
      });
      if (withInvest) {
        $(".left_menu div:last-child").addClass("left_menu__item--invest").append("<i class='left_menu__item__icon icon-attach_money'></i>");
      }
      if (oopt[entity_key][0].isNP) {
        color = new Cesium.Color.fromCssColorString('#a66d61');
        $(".left_menu div:last-child").addClass('np');
      }
      if (oopt[entity_key][0].isZP) {
        color = new Cesium.Color.fromCssColorString('#7ab342');
        $(".left_menu div:last-child").addClass('zp');
      }
      if (oopt[entity_key][0].isFZ) {
        color = new Cesium.Color.fromCssColorString('#d8b366');
        $(".left_menu div:last-child").addClass('fz');
      }
      rect = get_oopt_rect(entity_key);
      center = Cesium.Rectangle.center(rect);
      center = [center.latitude, center.longitude];
      oopt[entity_key].center = center;
      billboards.add({
        image: 'images/pin.png',
        position: Cesium.Cartesian3.fromRadians(center[1], center[0], 20000),
        horizontalOrigin: Cesium.HorizontalOrigin.Center,
        verticalOrigin: Cesium.VerticalOrigin.BOTTOM,
        id: entity_key,
        color: color,
        translucencyByDistance: new Cesium.NearFarScalar(1500000, 0, 1600000, 1),
        scaleByDistance: new Cesium.NearFarScalar(1.5e2, 1.5, 1.5e7, 0.75)
      });
    }
    return load_borders();
  };

  load_borders = function() {
    var border_source;
    border_source = new Cesium.GeoJsonDataSource();
    return border_source.load(settings.layerPath + 'federal_dv.topojson', {
      clampToGround: true
    }).then(function() {
      var b_entities, b_entitiy, j, len, positions, results;
      b_entities = border_source.entities.values;
      results = [];
      for (j = 0, len = b_entities.length; j < len; j++) {
        b_entitiy = b_entities[j];
        positions = b_entitiy.polygon.hierarchy.getValue().positions;
        results.push(primitives.add(new Cesium.Primitive({
          geometryInstances: new Cesium.GeometryInstance({
            geometry: new Cesium.PolylineGeometry({
              positions: positions,
              width: 1.0,
              vertexFormat: Cesium.PolylineColorAppearance.VERTEX_FORMAT
            }),
            attributes: {
              color: Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color.fromCssColorString('rgba(153,153,153, .67)'))
            }
          }),
          appearance: new Cesium.PolylineColorAppearance()
        })));
      }
      return results;
    }, load_cities());
  };

  load_cities = function() {};

  handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);

  ellipsoid = scene.globe.ellipsoid;

  handler.setInputAction((function(movement) {
    var polygon, polygon_name, rect;
    if (selected_polygon_name !== "") {
      close_menu();
    }
    polygon = scene.drillPick(movement.position)[0];
    if (polygon) {
      if ((typeof polygon.id) === "string") {
        polygon_name = polygon.id;
      } else {
        polygon_name = polygon.id.properties["Name_" + lang];
      }
      selected_polygon_name = polygon_name;
      rect = get_oopt_rect(polygon_name);
      scene.camera.flyTo({
        destination: rect
      });
      selected_polygon_name = polygon_name;
      return setTimeout(open_menu, 100);
    }
  }), Cesium.ScreenSpaceEventType.LEFT_CLICK);

  get_oopt_rect = function(name) {
    var _points, cartographics, j, len, polygon, rect, ref;
    _points = [];
    ref = oopt[name];
    for (j = 0, len = ref.length; j < len; j++) {
      polygon = ref[j];
      _points = _points.concat(polygon.polygon.hierarchy.getValue().positions);
    }
    cartographics = Cesium.Ellipsoid.WGS84.cartesianArrayToCartographicArray(_points);
    cartographics = cartographics.filter(function(val) {
      return val.height === 0;
    });
    rect = Cesium.Rectangle.fromCartographicArray(cartographics);
    rect.south -= Math.abs(rect.south - rect.north) * 0.6;
    rect.north += Math.abs(rect.south - rect.north) * 0.1;
    return rect;
  };

  cities = [
    {
      "coordinates": [37.61325, 55.748],
      "name": "Moscow"
    }, {
      "coordinates": [73.35733, 54.91536],
      "name": "Omsk"
    }, {
      "coordinates": [104.18426, 52.19257],
      "name": "Irkutsk"
    }, {
      "coordinates": [134.85471, 48.5309],
      "name": "Khabarovsk"
    }
  ];

  $('.home_btn').on('click', function() {
    return fly_to_home();
  });

  $('.map_selector').on('click', function(e) {
    if (e.offsetX > 177 / 2) {
      bing_map.alpha = 1;
      osm_map.alpha = 0;
      pole_primitive.show = false;
      $('.map_selector_fader').transition({
        x: 0
      }, 100, 'ease');
    } else {
      osm_map.alpha = 1;
      bing_map.alpha = 0;
      pole_primitive.show = true;
      $('.map_selector_fader').transition({
        x: -93
      }, 100, 'ease');
    }
    return e.stopPropagation();
  });

  $('.popup_menu').on('click', function(e) {
    return e.stopPropagation();
  });

  $("[data-target]").on('click', function(e) {
    e.preventDefault();
    if (!$(this).hasClass("disabled")) {
      return open_popup($(this).data("target"));
    }
  });

  check_buttons = function() {
    $('[data-target = photo], [data-target = video], [data-target = route], [data-target = investment]').removeClass("disabled");
    if (current_popup_data.images === 0) {
      $('[data-target = photo]').addClass("disabled");
    }
    if (!current_popup_data.video) {
      $('[data-target = video]').addClass("disabled");
    }
    if (!current_popup_data.route) {
      $('[data-target = route]').addClass("disabled");
    }
    if (!current_popup_data.invest) {
      return $('[data-target = investment]').addClass("disabled");
    }
  };

  open_menu = function() {
    var element, j, len, ref, selected_id;
    selected_id = oopt[selected_polygon_name]._id;
    prepare_popup(selected_id);
    $('.info-panel').removeClass("info-panel--hidden");
    ref = oopt[selected_polygon_name];
    for (j = 0, len = ref.length; j < len; j++) {
      element = ref[j];
      element.polygon.outline = new Cesium.ConstantProperty(true);
      element.polygon.outlineColor = new Cesium.ColorMaterialProperty(new Cesium.Color(1, 1, 1, 1));
    }
    return $('.left_menu div').each(function() {
      $(this).removeClass('selected_item');
      if ($(this).text() === selected_polygon_name) {
        return $(this).addClass('selected_item');
      }
    });
  };

  close_menu = function() {
    var element, j, len, ref, results;
    $('.left_menu div').removeClass('selected_item');
    $('.info-panel').addClass("info-panel--hidden");
    close_popup();
    current_popup_data = {};
    ref = oopt[selected_polygon_name];
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      element = ref[j];
      element.polygon.outline = new Cesium.ConstantProperty(false);
      results.push(element.polygon.outlineColor = new Cesium.ColorMaterialProperty(new Cesium.Color(1, 1, 1, 0)));
    }
    return results;
  };

  $(document).on('click', function() {
    $(".copyright__info__close").click();
    if (selected_polygon_name !== "") {
      return close_menu();
    }
  });

  open_popup = function(target) {
    var dataImg, targetPanel;
    targetPanel = $(".popup__panel--" + target);
    $('.popup:hidden').show();
    $('.popup__panel').hide();
    $(".popup__subtitle--invest").hide();
    $(".popup__subtitle--routes").hide();
    if (!$('video')[0].paused) {
      $('video')[0].pause();
    }
    targetPanel.show();
    targetPanel.scrollTop(0);
    if (target === "video") {
      $('video')[0].play();
    }
    if (target === "photo") {
      dataImg = get_img(current_popup_data.id, "photo", current_popup_data.images);
      build_gallery(dataImg, $(".photo-gallery"));
    }
    if (target === "route") {
      build_routes(current_popup_data.id);
    }
    if (target === "investment") {
      return build_investment(current_popup_data.id);
    }
  };

  close_popup = function() {
    $('.popup').fadeOut();
    if (!$('video')[0].paused) {
      $('video')[0].pause();
    }
    $(".popup__subtitle--invest").hide();
    return $(".popup__subtitle--routes").hide();
  };

  $('.close_popup').on('click', function(e) {
    close_popup();
    return e.preventDefault();
  });

  $('.popup').on('click', function(e) {
    return e.stopPropagation();
  });

  prepare_popup = function(_id) {
    var dta, j, len, second_name;
    current_popup_data = {};
    for (j = 0, len = popups_data.length; j < len; j++) {
      dta = popups_data[j];
      if (dta.id === "" + _id) {
        current_popup_data = dta;
      }
    }
    check_buttons();
    if (oopt[selected_polygon_name][0].isNP) {
      second_name = {
        "en": "National Park",
        "ru": "Национальный парк"
      }[lang];
    }
    if (oopt[selected_polygon_name][0].isZP) {
      second_name = {
        "en": "Nature Reserve",
        "ru": "Заповедник"
      }[lang];
    }
    if (oopt[selected_polygon_name][0].isFZ) {
      second_name = {
        "en": "Federal reserve",
        "ru": "Заказник"
      }[lang];
    }
    $('.popup__title').text(selected_polygon_name + " " + second_name);
    $('.info-panel__title').text(selected_polygon_name);
    $('.info-panel__subtitle').text(second_name);
    build_info(current_popup_data.id);
    if (current_popup_data.video) {
      return build_video(current_popup_data.id);
    }
  };

  get_img = function(id, folder, num) {
    var i, images, j, ref;
    images = [];
    for (i = j = 1, ref = num; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      images.push({
        img: settings.dataPath + id + '/' + folder + '/' + i + '.jpg'
      });
    }
    return images;
  };

  build_gallery = function(dataImg, container) {
    var fotorama;
    if (dataImg.length !== 0) {
      if (dataImg.length === 1) {
        container.addClass("fotorama--one-image");
      } else {
        container.removeClass("fotorama--one-image");
      }
      fotorama = container.data("fotorama");
      if (fotorama) {
        fotorama.show(0);
        return fotorama.load(dataImg);
      } else {
        container.fotorama({
          data: dataImg
        });
        return fotorama = container.data("fotorama");
      }
    }
  };

  build_info = function(_id) {
    var info_url;
    info_url = {
      "en": settings.dataPath + _id + "/index.html",
      "ru": settings.dataPath + _id + "/index_ru.html"
    }[lang];
    return insertByAjax(info_url, $(".popup__panel--info"));
  };

  build_routes = function(_id) {
    var dataImg, route_url;
    $(".popup__subtitle--routes").show();
    route_url = {
      "en": settings.dataPath + _id + "/routes.html",
      "ru": settings.dataPath + _id + "/routes_ru.html"
    }[lang];
    insertByAjax(route_url, $(".popup__panel--route .popup__panel__text"));
    dataImg = get_img(current_popup_data.id, "photo_route", current_popup_data.route_images);
    return build_gallery(dataImg, $(".routes-gallery"));
  };

  build_investment = function(_id) {
    var dataImg, investment_url;
    $(".popup__subtitle--invest").show();
    investment_url = {
      "en": settings.dataPath + _id + "/invest.html",
      "ru": settings.dataPath + _id + "/invest_ru.html"
    }[lang];
    insertByAjax(investment_url, $(".popup__panel--investment .popup__panel__text"));
    dataImg = get_img(current_popup_data.id, "photo_invest", current_popup_data.invest_images);
    return build_gallery(dataImg, $(".invest-gallery"));
  };

  build_video = function(_id) {
    var video_parent;
    video_parent = $('video').parent();
    $('video').remove();
    video_parent.append('<video></video>');
    $('video').attr('src', settings.dataPath + _id + '/video/1.mov');
    $('video').attr('src-mp4', settings.dataPath + _id + '/video/1.mp4');
    $('video').attr('preload', 'metadata');
    $('video').attr('controls', 'true');
    return $("video").on("error", function() {
      if ($('video').attr('src') !== $('video').attr('src-mp4')) {
        return $('video').attr('src', $('video').attr('src-mp4'));
      }
    });
  };

}).call(this);

//# sourceMappingURL=script.js.map
